
--Employee Names
SELECT NAME
FROM EMPLOYEE
ORDER BY NAME;

--Employee Salaries
SELECT NAME
FROM EMPLOYEE
WHERE SALARY > 2000
	AND MONTHS < 10
ORDER BY EMPLOYEE_ID ASC;

--The Blunder
SELECT CEIL(AVG(SALARY) - AVG(REPLACE(SALARY, 0, '')))
FROM EMPLOYEES

--Top Earners
SELECT (MONTHS * SALARY) AS TOTAL_EARNINGS, COUNT(*)
FROM EMPLOYEE
GROUP BY TOTAL_EARNINGS
ORDER BY TOTAL_EARNINGS LIMIT 1;