# root 사용자로 진행

# 계정생성
# BM
CREATE USER BM IDENTIFIED BY 'qwe123!@#QWE';
SHOW GRANTS FOR BM;


# 권한 부여
GRANT SELECT, INSERT ON mc_sql.* TO 'BM';


# ROLE
CREATE ROLE WEB_DEV;
GRANT SELECT, UPDATE, DELETE, INSERT ON mc_sql.employee TO 'WEB_DEV';


# 권한 회수
REVOKE SELECT, INSERT ON mc_sql.* FROM BM;
REVOKE SELECT, INSERT ON mc_sql.employee FROM 'WEB_DEV';