# DDL
# TYPE

CREATE TABLE TB_TYPE (
	T_TYNYINT TINYINT,
    T_SMALLINT SMALLINT,
    T_MIDIUMINT MEDIUMINT,
    T_INT INT,
    T_BIGINT BIGINT,
    
    T_FLOAT FLOAT,
    T_DOUBLE DOUBLE,
    T_DECIMAL DECIMAL(5, 3),
    
    T_BOOL BOOL,
    
    T_CHAR CHAR(10),
    T_VARCHAR VARCHAR(100),
    
    T_LONGTEXT LONGTEXT,
    
    T_DATE DATE,
    T_TIME TIME,
    T_DATETIME DATETIME,
    T_TIMESTAMP TIMESTAMP
    );