# 문자타입
INSERT INTO TB_TYPE(T_CHAR) VALUES('HELLO CHAR');
SELECT * FROM TB_TYPE;


INSERT INTO TB_TYPE(T_VARCHAR) VALUES('HELLO VARCHAR');
SELECT * FROM TB_TYPE;


INSERT INTO TB_TYPE(T_LONGTEXT) VALUES('HELLO LONGTEXT');
SELECT * FROM TB_TYPE;